### ISSUE TITLE
might be not compatible with lastest ddc framework

### ISSUE THREAD

**Issue by ccshao** [matsui54/ddc-converter_truncate#13]
Thanks for the this handy addon.

In my setting it is not working with latest ddc. 
```
call ddc#custom#patch_global('filterParams', {
  \ 'converter_truncate': {
  \    'maxAbbrWidth': 40,
  \    'maxKindWidth':20,
  \    'maxMenuWidth':40},
  \ })
```

In the screenshot, the long word was not truncated.
<img width="722" alt="Screenshot 2023-01-01 at 20 26 21" src="https://user-images.githubusercontent.com/4980631/210182504-af49df33-6f21-4c65-8faa-c2a69509c7eb.png">

Happy new year and many thanks for taking care of it!

**Comment by ccshao** [comment]
any updates on this? Many thanks!

**Comment by matsui54** [comment]
Sorry for the delay.
I tried with this minimal config and it seems to work.
```vim
set runtimepath+=~/.cache/dein/repos/github.com/vim-denops/denops.vim
set rtp+=~/.cache/dein/repos/github.com/Shougo/ddc.vim
set rtp+=~/.cache/dein/repos/github.com/Shougo/ddc-around
set rtp+=~/.cache/dein/repos/github.com/Shougo/ddc-ui-pum
set rtp+=~/.cache/dein/repos/github.com/Shougo/pum.vim
set rtp+=~/.cache/dein/repos/github.com/matsui54/ddc-converter_truncate

call ddc#custom#patch_global('sources', ['around'])
call ddc#custom#patch_global('ui', 'pum')
call ddc#custom#patch_global('sourceOptions', {
      \ '_': {'converters': ['converter_truncate'], 'sorters': []},
      \ })

call ddc#custom#patch_global('filterParams', {
  \ 'converter_truncate': {
  \    'maxAbbrWidth': 40,
  \    'maxKindWidth':20,
  \    'maxMenuWidth':40},
  \ })
call ddc#enable()
```

Screenshot
![image](https://user-images.githubusercontent.com/63794197/228463300-4eced7be-43b6-4e0b-ae1d-defe2043db15.png)


Can you check your configuration again?

**Comment by ccshao** [comment]
Thanks for the example codes! Yes pum ui works. I was using the native ui and that is not compatible. Sorry I didn’t make myself clear in the beginning.


在 29.03.2023，09:50，Haruki Matsui ***@***.***> 写道：

﻿

Sorry for the delay.
I tried with this minimal config and it seems to work.

set runtimepath+=~/.cache/dein/repos/github.com/vim-denops/denops.vim
set rtp+=~/.cache/dein/repos/github.com/Shougo/ddc.vim
set rtp+=~/.cache/dein/repos/github.com/Shougo/ddc-around
set rtp+=~/.cache/dein/repos/github.com/Shougo/ddc-ui-pum
set rtp+=~/.cache/dein/repos/github.com/Shougo/pum.vim
set rtp+=~/.cache/dein/repos/github.com/matsui54/ddc-converter_truncate

call ddc#custom#patch_global('sources', ['around'])
call ddc#custom#patch_global('ui', 'pum')
call ddc#custom#patch_global('sourceOptions', {
      \ '_': {'converters': ['converter_truncate'], 'sorters': []},
      \ })

call ddc#custom#patch_global('filterParams', {
  \ 'converter_truncate': {
  \    'maxAbbrWidth': 40,
  \    'maxKindWidth':20,
  \    'maxMenuWidth':40},
  \ })
call ddc#enable()

Screenshot
[image]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F63794197%2F228463300-4eced7be-43b6-4e0b-ae1d-defe2043db15.png&data=05%7C01%7C%7C5a5992b2c56f4210056d08db302a4094%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638156730253421161%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5a0SBzpakabevOk0ZB2BB9A6b2lm5Gg0nnsgTLMevYU%3D&reserved=0>

Can you check your configuration again?

**Comment by matsui54** [comment]
> I was using the native ui and that is not compatible.

Really? With the following settings, it works!
```vim
set runtimepath+=~/.cache/dein/repos/github.com/vim-denops/denops.vim
set rtp+=~/.cache/dein/repos/github.com/Shougo/ddc.vim
set rtp+=~/.cache/dein/repos/github.com/Shougo/ddc-around
set rtp+=~/.cache/dein/repos/github.com/Shougo/ddc-ui-native
" set rtp+=~/.cache/dein/repos/github.com/Shougo/pum.vim
set rtp+=~/.cache/dein/repos/github.com/matsui54/ddc-converter_truncate

call ddc#custom#patch_global('sources', ['around'])
" call ddc#custom#patch_global('ui', 'pum')
call ddc#custom#patch_global('ui', 'native')
call ddc#custom#patch_global('sourceOptions', {
      \ '_': {'converters': ['converter_truncate'], 'sorters': []},
      \ })

call ddc#custom#patch_global('filterParams', {
  \ 'converter_truncate': {
  \    'maxAbbrWidth': 40,
  \    'maxKindWidth':20,
  \    'maxMenuWidth':40},
  \ })
call ddc#enable()

```

**Comment by ccshao** [comment]
Thanks for th update!
Yes, you are right. Now I am confused why it didn't work in my setting for quite a while. Maybe some misconfigurations.
